name: frappe_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.9.4+1073

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter_image_slideshow: any
  flutter_js: ^0.8.5
  device_preview:
  weather_icons: ^3.0.0
  flutter_mentions:
  draggable_home: ^1.0.5
  flutter_settings_ui:
  salomon_bottom_bar: ^3.3.2
  photo_view:
  lottie: ^3.3.1
  shamsi_date: ^1.1.1
  logger: ^2.6.1
  flutter_easyloading:
  #  html_editor_enhanced:
  flutter_typeahead: ^5.2.0
  flutter_chips_input:
    git:
      url: https://github.com/danvick/flutter_chips_input
      ref: cb30c04cfcf8183ec77b664aae1144b70829473d
  timelines: ^0.1.0
  persistent_bottom_nav_bar: ^6.2.1
  overflow_view: ^0.5.0
  get: ^4.7.2
  injectable: ^2.4.1
  json_table:
  barcode_widget: ^2.0.4
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  device_info_plus: ^11.5.0
#  flutter_local_notifications: ^19.4.1
  # workmanager: ^0.4.0
  get_it: ^8.2.0
  fluttertoast: 8.2.12
  geolocator: 9.0.2
  pinput: ^5.0.0
  flutter_map: 5.0.0
  image_picker: ^1.2.0
  persian_datetime_picker: ^3.1.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^6.1.5
  provider: ^6.1.5+1
  open_filex: ^4.4.0
  flutter_svg: ^2.2.0
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  file_picker: ^10.3.2
  flutter_form_builder: ^10.1.0
  form_builder_validators:
  flutter_pagewise: ^2.0.4
  html: ^0.15.4
  url_launcher: ^6.2.6
  permission_handler: ^12.0.1

  timeago: ^3.6.1
  path_provider: ^2.1.3
  flutter_html:
  dio: ^5.4.3+1
  dropdown_search: 6.0.2
  gradient_icon: ^2.0.9
  dio_cookie_manager: ^3.1.1
  flutter_image_compress: ^2.4.0
  form_builder_extra_fields: ^12.1.0
  carousel_slider: ^5.0.0
  autocomplete_textfield: ^2.0.1
  animate_do: ^4.2.0


  intl:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:
  build_runner:
  json_serializable: ^6.8.0
  injectable_generator:
  hive_generator: 2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/frappe_icon.jpg"

dependency_overrides:
  flutter_colorpicker: 1.1.0

  flutter_plugin_android_lifecycle: 2.0.21




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/

  fonts:

    - family: Estedad-VF
      fonts:
        - asset: fonts/Estedad-FD-SemiBold.ttf
    - family: Iran Sans Bold
      fonts:
        - asset: assets/fonts/Iran Sans Bold.ttf
          weight: 500

    - family: Iran Sans
      fonts:
        - asset: assets/fonts/B nanzanin.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
